name: Daily Pump Token Scraper

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3:00 UTC
  workflow_dispatch:      # Allow manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run scraper
        run: python data/scrape_pump_tokens.py

      - name: Commit & push pump_tokens.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/pump_tokens.json
          git commit -m "Update pump_tokens.json [auto]"
          git push
